services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
    ports:
      - '3100:3100'
  mysql-container:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - ~/datas/data-mysql:/var/lib/mysql