version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
    ports:
      - '3100:3100'
    networks:
      - common-network
  mysql-container:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - /root/datas/data-mysql:/var/lib/mysql
    networks:
      - common-network
networks:
    common-network:
      driver: bridge